# Generated by Django 5.1.5 on 2025-02-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_img_url',
            field=models.ImageField(default='', max_length=500, upload_to=''),
        ),
    ]
