# Generated by Django 5.1.5 on 2025-03-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cateringbooking',
            old_name='notes',
            new_name='special_requests',
        ),
        migrations.AddField(
            model_name='cateringbooking',
            name='event_type',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='cateringbooking',
            name='menu_preference',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='cateringbooking',
            name='time',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
