# Generated by Django 5.1.5 on 2025-03-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0003_rename_notes_cateringbooking_special_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='food_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BEVRAGE', 'Bevrage'), ('DESSERT', 'Dessert'), ('SNACKS', 'Snacks')], max_length=40),
        ),
    ]
