# Generated by Django 5.1.5 on 2025-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0003_cateringbooking_alter_food_food_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelreservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
