# Generated by Django 5.1.5 on 2025-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0004_tabelreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelreservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
