# Generated by Django 5.1.5 on 2025-04-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0005_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='overallBack_food_id_6f9eed_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='overallBack_food_id_7b10e6_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='content',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overallBackend.food'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overallBackend.food'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
