# Generated by Django 5.1.5 on 2025-03-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0005_alter_tabelreservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringbooking',
            name='location',
        ),
    ]
