# Generated by Django 5.1.5 on 2025-03-22 16:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0005_alter_food_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='food_name', unique=True),
        ),
    ]
