# Generated by Django 5.1.5 on 2025-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0006_alter_food_food_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='food_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('BRUNCH', 'Brunch'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BEVRAGE', 'Bevrage'), ('DESSERT', 'Dessert'), ('APPETIZERS', 'Appetizers'), ('SNACKS', 'Snacks'), ('BUFFET', 'Buffet'), ('SMOOTIES', 'Smooties')], max_length=40),
        ),
    ]
