# Generated by Django 5.1.5 on 2025-03-10 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0006_remove_cateringbooking_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('No_of_person', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('Booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
