# Generated by Django 5.1.5 on 2025-03-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0007_tablereservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='view',
        ),
        migrations.DeleteModel(
            name='TableReservations',
        ),
    ]
