# Generated by Django 5.1.5 on 2025-04-26 04:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0007_remove_rating_food_remove_rating_user_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_paid', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', help_text='Indicates if the payment has been completed', max_length=6)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash')], default='cash', help_text='Method used for payment', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_reference', models.CharField(blank=True, help_text='Payment gateway transaction ID (if applicable)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='overallBackend.cartitem')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
