# Generated by Django 5.1.5 on 2025-03-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0008_remove_food_view_delete_tablereservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_slug',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overallBackend.foodtype'),
        ),
        migrations.AlterField(
            model_name='food',
            name='taste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='overallBackend.foodtaste'),
        ),
        migrations.AlterField(
            model_name='foodtaste',
            name='taste_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='food_type',
            field=models.CharField(max_length=100),
        ),
    ]
