# Generated by Django 5.1.5 on 2025-04-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_reference',
        ),
    ]
