# Generated by Django 5.1.5 on 2025-03-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0009_remove_table_reserved_at_remove_table_reserved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_email',
        ),
    ]
