# Generated by Django 5.1.5 on 2025-03-17 08:49

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0009_remove_food_food_slug_alter_food_food_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='food_name', unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_img_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overallBackend.foodtype'),
        ),
        migrations.AlterField(
            model_name='food',
            name='taste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overallBackend.foodtaste'),
        ),
        migrations.AlterField(
            model_name='foodtaste',
            name='taste_type',
            field=models.CharField(choices=[('VEG', 'veg'), ('NON-VEG', 'non-veg')], max_length=40),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='food_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BEVRAGE', 'Bevrage'), ('DESSERT', 'Dissert')], max_length=40),
        ),
    ]
