# Generated by Django 5.1.5 on 2025-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtaste',
            name='taste_type',
            field=models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG'), ('DRINKS', 'DRINKS'), ('SNACKS', 'SNACKS')], max_length=40),
        ),
    ]
