# Generated by Django 5.1.5 on 2025-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0011_alter_foodtaste_taste_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash on Delivery')], default='cash', help_text='Method used for payment', max_length=20),
        ),
    ]
