# Generated by Django 5.1.5 on 2025-03-28 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0011_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='User',
            new_name='user',
        ),
    ]
