# Generated by Django 5.1.5 on 2025-03-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0013_cartitem_created_at_cartitem_user_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
