# Generated by Django 5.1.5 on 2025-03-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0014_remove_cartitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabelReservation',
        ),
    ]
