# Generated by Django 5.1.5 on 2025-04-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overallBackend', '0016_alter_feedback_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
